### ISSUE TITLE
Minor To-Do

### ISSUE THREAD

**Issue by ofelizestevez** [Haccfoundation/Haccfoundation.github.io#3]
-  [x] Add Email links
   - [x] Footer
   - [x] Opportunities
-  [x] Add Phone Links
   - [x] Footer
-  [x] Add Address Links
   - [x] Footer
